var Easing_Linear;
var Easing_Quadratic;
var Easing_Cubic;
var Easing_Quartic;
var Easing_Quintic;
var Easing_Sinusoidal;
var Easing_Exponential;
var Easing_Circular;
var Easing_Elastic;
var Easing_Back;
var Easing_Bounce;
export { Easing_Linear as Linear, Easing_Quadratic as Quadratic };
